export const MAIMAI_FESTIVAL_UNLOCKS = {
  songs: [
    '康莊大道',
    '"411Ψ892"',
    '星見草',
    'Beat Opera op.1',
    '群青シグナル',
    'ピリオドサイン',
    'RIFFRAIN',
    'Falling',
    'VSpook!',
    '#狂った民族２ PRAVARGYAZOOQA',
    'Neon Kingdom',
    'You Mean the World to Me',
    '[X]',
    'Tricolor⁂circuS',
    'Rainbow Rush Story',
    'ホシシズク',
    'Hainuwele',
    '電光石火',
    '最強STRONGER',
    'Aegleseeker',
  ],
  dxCharts: [
    'ケロ⑨destiny',
    '響縁',
    '火炎地獄',
    'M.S.S.Planet',
    'モザイクロール',
  ],
  stdCharts: [
    'VIIIbit Explorer',
  ],
};

export const MAIMAI_UNIVERSE_PLUS_UNLOCKS = {
  songs: [
    'Jouez Avec Moi?',
    "World's end loneliness",
    '白花の天使',
    'Metamorphosism',
    'WiPE OUT MEMORIES',
    'OTOGEMA',
    'Sage',
    'チューリングの跡',
    '星空パーティーチューン',
    'Swift Swing',
    'N3V3R G3T OV3R',
    'HAGAKIRI',
    'Irresistible',
    'HECATONCHEIR',
    'Strive against fate',
    'パラマウント☆ショータイム！！',
    'ｉｓｏｐｈｏｔｅ',
    'ミルキースター・シューティングスター',
  ],
  dxCharts: ['セツナトリップ', 'Grip & Break down !!'],
};
